name: Deploy Service

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Branch to fetch environment files from"
        required: true
        default: "unified-env-lts"
      env_file:
        description: "Environment file to use (set manually after fetching the list)"
        required: true
      cluster_name:
        description: "EKS cluster name to log in to"
        required: true
      region:
        description: "AWS region of the EKS cluster"
        required: true
        default: "ap-south-1"
      docker_image:
        description: "Docker image to deploy (e.g., egov-mdms-service:core-2.9-lts)"
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy-docker-image:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the branch
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch_name }}

      # Step 2: Fetch and Source the Env File
      - name: Fetch and Source Env File
        id: fetch_env
        run: |
          ENV_FILE_PATH="./deploy-as-code/helm/environments/${{ github.event.inputs.env_file }}"
          if [ ! -f "$ENV_FILE_PATH" ]; then
            echo "Error: The specified environment file $ENV_FILE_PATH does not exist"
            exit 1
          fi
          echo "Using environment file: $ENV_FILE_PATH"
          DOMAIN_NAME=$(yq e '.global.domain' $ENV_FILE_PATH)
          if [ -z "$DOMAIN_NAME" ]; then
            echo "Error: Domain name not found in the environment file"
            exit 1
          fi
          echo "Domain Name: $DOMAIN_NAME"
          echo "DOMAIN_NAME=$DOMAIN_NAME" >> $GITHUB_ENV

      # Step 3: Fetch Container Registry Config
      - name: Fetch Container Registry
        id: fetch_registry
        run: |
          COMMON_VALUES_PATH="./deploy-as-code/helm/common/values.yaml"
          if [ ! -f "$COMMON_VALUES_PATH" ]; then
            echo "Error: Common values file $COMMON_VALUES_PATH does not exist"
            exit 1
          fi
          CONTAINER_REGISTRY=$(yq e '.global.containerRegistry' $COMMON_VALUES_PATH)
          if [ -z "$CONTAINER_REGISTRY" ]; then
            echo "Error: Container registry not found in common values"
            exit 1
          fi
          echo "Container Registry: $CONTAINER_REGISTRY"
          echo "CONTAINER_REGISTRY=$CONTAINER_REGISTRY" >> $GITHUB_ENV

      # Step 4: Install or Update AWS CLI
      - name: Install or Update AWS CLI
        run: |
          if aws --version &>/dev/null; then
            echo "AWS CLI is already installed. Skipping installation."
          else
            echo "AWS CLI not found. Installing..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
          fi
          aws --version

      # Step 5: Configure AWS CLI
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region ${{ github.event.inputs.region }}

      # Step 6: Generate kubeconfig for EKS
      - name: Generate kubeconfig for EKS
        run: |
          echo "Generating kubeconfig for EKS cluster: ${{ github.event.inputs.cluster_name }}"
          aws eks update-kubeconfig --name ${{ github.event.inputs.cluster_name }} --region ${{ github.event.inputs.region }}
          kubectl config view

      # Step 7: Verify Cluster Login
      - name: Verify Cluster Login
        run: |
          echo "Attempting to log in to Kubernetes cluster"
          kubectl get nodes

      # Step 8: Deploy Service
      - name: Deploy Service
        run: |
          echo "Logging into Docker registry..."
          echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          # Input: Docker image name
          DOCKER_IMAGE=${{ github.event.inputs.docker_image }}
          SERVICE_NAME=$(echo "$DOCKER_IMAGE" | cut -d':' -f1)

          # Define DB image using dynamic registry
          DB_IMAGE="${CONTAINER_REGISTRY}/$SERVICE_NAME-db:${DOCKER_IMAGE##*:}"
          echo "Application Image: $DOCKER_IMAGE"
          echo "Database Image: $DB_IMAGE"

          # Check if the DB image exists
          echo "Checking if the database image exists..."
          if docker pull "$DB_IMAGE" &>/dev/null; then
            echo "Database image found: $DB_IMAGE"
            DB_EXISTS=true
          else
            echo "Database image not found. Only deploying the application container."
            DB_EXISTS=false
          fi

          CHARTS_DIR="./deploy-as-code/helm/charts"
          CHART_DIR=$(find "$CHARTS_DIR" -type d -name "$SERVICE_NAME" -exec test -f {}/Chart.yaml \; -print -quit)
          if [ -z "$CHART_DIR" ]; then
            echo "Error: No Helm chart found for service '$SERVICE_NAME' in $CHARTS_DIR."
            exit 1
          fi
          echo "Found Helm chart for '$SERVICE_NAME' at: $CHART_DIR"

          NAMESPACE=$(yq e '.namespace // "egov"' "$CHART_DIR/values.yaml")
          echo "Using namespace: $NAMESPACE"

          if [ "$DB_EXISTS" = true ]; then
            helm upgrade --install "$SERVICE_NAME" "$CHART_DIR" \
              --namespace "$NAMESPACE" \
              -f "$CHART_DIR/values.yaml" \
              --set image.tag="${DOCKER_IMAGE##*:}" \
              --set initContainers.dbMigration.image.tag="${DB_IMAGE##*:}" \
              --set global.domain="$DOMAIN_NAME" \
              --set db.image.repository="${CONTAINER_REGISTRY}/$SERVICE_NAME-db"
          else
            helm upgrade --install "$SERVICE_NAME" "$CHART_DIR" \
              --namespace "$NAMESPACE" \
              -f "$CHART_DIR/values.yaml" \
              --set image.tag="${DOCKER_IMAGE##*:}" \
              --set global.domain="$DOMAIN_NAME"
          fi
        shell: /usr/bin/bash -e {0}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DOCKER_IMAGE: ${{ github.event.inputs.docker_image }}
