name: Deploy Docker Image with Env File

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Branch to fetch environment files from"
        required: true
        default: "master"
      env_file:
        description: "Environment file to use (set manually after fetching the list)"
        required: true
      cluster_name:
        description: "EKS cluster name to log in to"
        required: true
      region:
        description: "AWS region of the EKS cluster"
        required: true
        default: "us-east-1"
      docker_image:
        description: "Docker image to deploy (e.g., my-app:latest)"
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  list-env-files:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the branch
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch_name }}

      # Step 2: List Environment Files
      - name: List Env Files in Branch
        run: |
          echo "Listing all environment files in branch: ${{ github.event.inputs.branch_name }}"
          find . -type f -name "*.env" || echo "No environment files found"
          echo "Manually select an environment file from the list above and re-trigger the workflow with the correct env_file input."
          exit 0

  deploy-docker-image:
    needs: list-env-files
    if: ${{ github.event.inputs.env_file != '' }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the branch
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch_name }}

      # Step 2: Fetch and Source the Env File
      - name: Fetch and Source Env File
        id: fetch_env
        run: |
          if [ ! -f "${{ github.event.inputs.env_file }}" ]; then
            echo "Error: The specified environment file ${{ github.event.inputs.env_file }} does not exist"
            exit 1
          fi
          echo "Using environment file: ${{ github.event.inputs.env_file }}"
          source ${{ github.event.inputs.env_file }}
          cat ${{ github.event.inputs.env_file }}

      # Step 3: Install AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update && sudo apt-get install -y awscli

      # Step 4: Configure AWS CLI
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region ${{ github.event.inputs.region }}

      # Step 5: Generate kubeconfig for EKS
      - name: Generate kubeconfig for EKS
        run: |
          echo "Generating kubeconfig for EKS cluster: ${{ github.event.inputs.cluster_name }}"
          aws eks update-kubeconfig --name ${{ github.event.inputs.cluster_name }} --region ${{ github.event.inputs.region }}
          kubectl config view

      # Step 6: Verify Cluster Login
      - name: Verify Cluster Login
        run: |
          echo "Attempting to log in to Kubernetes cluster"
          kubectl get nodes

      # Step 7: Deploy Docker Image
      - name: Deploy Docker Image
        run: |
          echo "Deploying Docker image: ${{ github.event.inputs.docker_image }}"
          kubectl set image deployment/my-deployment my-container=${{ github.event.inputs.docker_image }}
          kubectl rollout status deployment/my-deployment
